Updaet
nosovk/mailchimp-form-external pull request #2
Opened 2020-11-01 21:37 UTC by HikariSenshi

Updated form due to requirements

2020-11-02 05:37 UTC, nosovk requested changes

2020-11-02 05:37 UTC, nosovk commented on src/App.js
> +        'Access-Control-Allow-Origin': '*'
'Access-Control-Allow-Origin': '*' - это тут лишнее

2020-11-02 05:37 UTC, nosovk commented on src/index.css
> +  font-family: Helvetica, serif;
в разных местах используется разный набор шрифтов, похоже пропущен линт

2020-11-02 05:42 UTC, nosovk commented on src/index.css
>    text-align: center;
не пускает написать коммент к строке, но ниже color: official; - такого цвета нет

2020-11-02 05:45 UTC, nosovk commented
файл Input.jsx никуда не импортируется - похоже он не используется

2020-11-02 05:56 UTC, nosovk commented on src/index.css
> +  font-family: Helvetica, serif;
вообще шрифты наследуются - в большинстве случаев тут можно удалить доп определения шрифтов

2020-11-02 05:57 UTC, nosovk commented
для h1 => text-transform: uppercase; ?

2020-11-03 10:32 UTC, HikariSenshi commented
> для h1 => text-transform: uppercase; ?

Это нужно для правильного отображения текста.  Такие же стили используются в оригинальной форме.

2020-11-03 10:32 UTC, HikariSenshi commented on src/index.css
>    text-align: center;
Убрал

2020-11-03 10:34 UTC, HikariSenshi commented on src/index.css
> +  font-family: Helvetica, serif;
Написано в соответствии с линтом

2020-11-03 10:35 UTC, nosovk commented
> > для h1 => text-transform: uppercase; ?
> 
> Это нужно для правильного отображения текста. Такие же стили используются в оригинальной форме.

там нет такого стиля, там текст капсом набит. Я потому и написал сделать CSS text-transform вместо текста капсом

2020-11-03 10:36 UTC, nosovk commented on src/index.css
> +  font-family: Helvetica, serif;
линт ругается на форму, я же говорю что тут по смыслу оно не нужно вообще, т.к. уже есть у родительского елемента

2020-11-03 10:37 UTC, nosovk commented on src/App.js
> +          <h1>РЕГИСТРАЦИОННАЯ ФОРМА ДЛЯ РАССЫЛКИ НОВОСТЕЙ И ПРАЙСОВ</h1>
вот тут оно капсом, про это был коммент про h1

2020-11-03 10:37 UTC, nosovk commented on src/App.js
>      }).catch((e) => console.log(e));
если уже есть тостер - кидай ошибку в тостер

2020-11-03 18:12 UTC, HikariSenshi commented on src/App.js
> +          <h1>РЕГИСТРАЦИОННАЯ ФОРМА ДЛЯ РАССЫЛКИ НОВОСТЕЙ И ПРАЙСОВ</h1>
+

2020-11-03 18:12 UTC, HikariSenshi commented on src/App.js
>      }).catch((e) => console.log(e));
+

2020-11-03 18:14 UTC, nosovk commented on src/App.js
>      }).catch((e) => console.log(e));
помоему уже писал, но смысл в том что у тебя есть тут ошибка, почему бы не вывести ошибку в тостер если он тоже у нас уже есть?

2020-11-03 21:26 UTC, HikariSenshi commented on src/App.js
>      }).catch((e) => console.log(e));
вывел.

2020-11-04 15:06 UTC, merged